### ISSUE TITLE
Valgrind test

### ISSUE THREAD

**Issue by paulfloyd** [clausecker/strperf#1]
Would it be possble to run this test suite under Valgrind?
(and ideally Valgrind built from source like https://sourceware.org/pub/valgrind/valgrind-3.22.0.RC1.tar.bz2)
My workstation is too ancient so it doesn't have the features to run the SIMD versions.

**Comment by clausecker** [comment]
Hi paulfloyd,

This is the benchmark set.  The unit tests are all part of FreeBSD's test suite.  It should be possible to run it under Valgrind regardless.

As for CPU features, right now the newest feature set required is SSE4.2.  Most code requires only SSE2, which is something every amd64 CPU needs to support.

**Comment by paulfloyd** [comment]
At last

Running in
src/lib/libc/tests/string

116/116 passed (0 failed)

I don't know how to get kyua to run each test under memcheck to I run the whole thing

/home/paulf/tools/valgrind/bin/valgrind --trace-children=yes -q --log-file=mc.%p.log kyua test -k Kyuafile

and no errors!

**Comment by clausecker** [comment]
Great!  Note that there are some functions currently under review, including `strcmp`, `strncmp`, `strrchr`, and `stpncpy`.  I'm currently working on `strlcpy` and will likely attempt `strstr` and `memmem`, too.
